### ISSUE TITLE
Seems to be broken since minetest commit fd87b04f

### ISSUE THREAD

**Issue by lhofhansl** [minetest-mods/playeranim#9] opened 2016-11-27 21:23 UTC
Looks like minetest_game's [fd87b04f](https://github.com/minetest/minetest_game/commit/fd87b04f3c510fd61797c6e79b76830f03f485b7
) breaks this. The arms are sicking up now. That commit changed the player model.

I looked at the code, but I do not have blender around to see what changed, so it's a bit hard for me to fix it (hence an issue and now pull request :( )

**Comment by sofar** [comment] 2016-11-27 22:33
Urgh, I tested those changes with this mod and I didn't spot any issues :/

**Comment by sofar** [comment] 2016-11-27 22:47
Tried agan, but it works on my system. The animations are choppy, but the arms look correct?

![](http://i.imgur.com/YDCXfud.png)

**Comment by lhofhansl** [comment] 2016-11-28 00:46
Hmm... Definitely broken here. Strange. Lemme try again.

**Comment by lhofhansl** [comment] 2016-11-28 00:52
![screenshot_20161127_165129](https://cloud.githubusercontent.com/assets/446130/20653392/ccd6aed6-b4c1-11e6-9336-16affe0a4a50.png)

This is with Playeranim's master branch (not the "old" branch).

**Comment by lhofhansl** [comment] 2016-11-28 06:03
@sfan5 Did you use the latest of the master branch? That works fine with stock 0.4.14, but not with current minetest master. It also worked a few days ago, and there were no recent changes in playeranim. I haven't bisected it, but fd87b04f seems like a very likely candidate.

**Comment by sofar** [comment] 2016-11-28 06:07
Turns out the `cozy` mod was installed. Without it I can reproduce this bug as well.

FYI, I haven't used 0.4.14 since it was released, I'm always on tip.

**Comment by lhofhansl** [comment] 2016-11-28 06:43
Didn't know about cozy, gonna try that.

(I think playeranim - at least the head-pitch animation- and cozy should be part of the default minetest_game. But that's a different discussion.)

**Comment by sofar** [comment] 2016-11-28 07:50
Well ideally core performs the head animation, and not lua. As you can see with playeranim it's horribly choppy.

**Comment by Rogier-5** [comment] 2016-11-28 09:52
The arm attachment points used to be closer to the body. It's strange that the arms would end up detached... However, as the default positions are hard-coded, it is not surprising that this mod would be affected. Ideally, the default positions would be obtained from minetest, but minetest can't provide them.

The default rotation of the arms and the cape did change for some reason (from 180° to 0° - which *is* more sensible IMO...). There were no explicit changes to the model that would cause this: they are unintended side effects (but not necessarily undesirable). So it's probably caused by something strange in blender, the export script or in irrlicht...

BTW: the 'normal' bone positions of the arms are strange (± 3.9). I wonder how this could have worked at all. The old attachment points were at ± 2 (now they are at ±3).

Actually: this *can* be explained: if the left and right arms were swapped, or if they were rotated 180° around their axes (i.e. around the bone).

**Comment by sofar** [comment] 2016-11-29 05:27
Should be easily fixable then?

**Comment by Rogier-5** [comment] 2016-11-29 08:47
Pushed a fix: #10

**Comment by Rui-Minetest** [comment] 2016-12-07 12:05
https://github.com/minetest-mods/playeranim/commit/0ca8e5a3aad630657d17ba801eede61cb1ff7065

**Closed by Rui-Minetest** 2016-12-07 12:05 UTC
